export const earningsNames = [
  "James",
  "Daniel",
  "Michael",
  "Sophia",
  "Ethan",
  "Olivia",
  "Noah",
  "Emma",
  "Liam",
  "Ava",
  "Elijah",
  "Mia",
  "Lucas",
  "Charlotte",
  "Mason",
  "Amelia",
  "Logan",
  "Harper",
  "Benjamin",
  "Evelyn",
  "Jacob",
  "Abigail",
  "Alexander",
  "Emily",
  "Henry",
  "Ella",
  "Sebastian",
  "Scarlett",
  "Jack",
  "Grace",
  "Owen",
  "Chloe",
  "Wyatt",
  "Victoria",
  "Leo",
  "Riley",
  "Gabriel",
  "Aria",
  "Julian",
  "Lily",
  "Matthew",
  "Layla",
  "David",
  "Zoey",
  "Joseph",
  "Nora",
  "Samuel",
  "Hannah",
  "Carter",
  "Stella",
  "Aiden",
  "Zoe",
  "John",
  "Leah",
  "Luke",
  "Hazel",
  "Isaac",
  "Ellie",
  "Dylan",
  "Paisley",
  "Andrew",
  "Aria",
  "John Turner",
  "Layla",
  "Christopher",
  "Sofia Parker",
  "Ryan Evans",
  "Nora Edwards",
  "Nathan",
  "Luna Stewart",
  "Aaron",
  "Stella Morris",
  "Isaac Rogers",
  "Bella Reed",
  "Dylan Cook",
  "Savannah",
  "Riley",
  "Julian Cox",
  "Penelope",
  "Leo Ward",
  "Violet Flores",
  "Hudson Barnes",
  "Skylar Diaz",
  "Levi Price",
  "Paisley",
  "Gabriel Wood",
  "Anthony",
  "Madison",
  "Lincoln Gray",
  "Eli Sanders",
  "Lydia Ross",
  "Ian Powell",
  "Peyton",
  "Jonathan",
  "Naomi",
  "Brandon Perry",
  "Alice Perry",
  "Victor Ross",
  "Claire",
  "Eric",
  "Eden Wood",
  "Adrian James",
  "Maria Gray",
  "Justin",
  "Isla Watson",
  "Jason",
  "Rose",
  "Kevin",
  "Lillian",
];

export const earningsCountries = [
  "canada",
  "germany",
  "brazil",
  "singapore",
  "australia",
  "france",
  "sweden",
  "japan",
  "spain",
  "norway",
  "netherlands",
  "italy",
  "switzerland",
  "belgium",
  "denmark",
  "ireland",
  "austria",
  "new zealand",
  "finland",
  "portugal",
  "south africa",
  "mexico",
  "argentina",
  "chile",
  "poland",
  "czech republic",
  "hungary",
  "romania",
  "greece",
  "turkey",
  "united kingdom",
  "united states",
  "uae",
  "qatar",
  "saudi arabia",
  "malaysia",
  "thailand",
  "indonesia",
  "philippines",
  "south korea",
  "pakistan",
  "ghana",
  "kenya",
  "egypt",
  "morocco",
  "luxembourg",
  "iceland",
  "estonia",
  "dubai",
];

export const earningsAmounts = [
  1120, 1450, 1780, 2015, 2450, 2890, 3150, 3520, 3980, 4210,
  4575, 4890, 5120, 5480, 5895, 6210, 6570, 6890, 7125, 7480,
  7817, 8050, 8420, 8795, 9150, 9480, 9820, 10350, 10890, 11420,
  11980, 12540, 13200, 13850, 14590, 15220, 15980, 16750, 17400, 18260,
  19120, 20500, 21480, 22650, 23900, 24870, 25990, 27150, 28600, 29840,
];