export const transactionNames = [
  "James Carter",
  "Olivia Smith",
  "Noah Johnson",
  "Emma Brown",
  "Liam Davis",
  "Sophia Wilson",
  "Mason Taylor",
  "Isabella Moore",
  "Ethan Anderson",
  "Mia Thomas",
  "Lucas Jackson",
  "Amelia White",
  "Aiden Harris",
  "Harper Martin",
  "Elijah Thompson",
  "Evelyn Garcia",
  "Daniel Scott",
  "Chloe Walker",
  "Henry Lewis",
  "Abigail Hall",
  "Matthew Young",
  "Ella King",
  "Sebastian Wright",
  "Grace Lopez",
  "Jack Hill",
  "Zoey Allen",
  "David Green",
  "Lily Adams",
  "Joseph Baker",
  "Hannah Nelson",
  "Samuel Carter",
  "Victoria Perez",
  "Andrew Mitchell",
  "Aria Roberts",
  "John Turner",
  "Layla Phillips",
  "Christopher Campbell",
  "Sofia Parker",
  "Ryan Evans",
  "Nora Edwards",
  "Nathan Collins",
  "Luna Stewart",
  "Aaron Sanchez",
  "Stella Morris",
  "Isaac Rogers",
  "Bella Reed",
  "Dylan Cook",
  "Savannah Morgan",
  "Caleb Bell",
  "Aurora Murphy",
  "Miles Bailey",
  "Hazel Rivera",
  "Wyatt Cooper",
  "Riley Richardson",
  "Julian Cox",
  "Penelope Howard",
  "Leo Ward",
  "Violet Flores",
  "Hudson Barnes",
  "Skylar Diaz",
  "Levi Price",
  "Paisley Bennett",
  "Gabriel Wood",
  "Brooklyn Brooks",
  "Anthony Watson",
  "Madison Kelly",
  "Lincoln Gray",
  "Aubrey James",
  "Jaxon Reyes",
  "Ellie Cruz",
  "Christian Hughes",
  "Scarlett Myers",
  "Jordan Long",
  "Mila Foster",
  "Eli Sanders",
  "Lydia Ross",
  "Ian Powell",
  "Peyton Butler",
  "Jonathan Barnes",
  "Naomi Jenkins",
  "Brandon Perry",
  "Alice Perry",
  "Carlos Powell",
  "Ruby Hughes",
  "Diego Flores",
  "Ivy Simmons",
  "Victor Ross",
  "Claire Price",
  "Eric Bennett",
  "Eden Wood",
  "Adrian James",
  "Maria Gray",
  "Justin Kelly",
  "Isla Watson",
  "Jason Brooks",
  "Rose Diaz",
  "Kevin Murphy",
  "Lillian Rivera",
];

export const transactionGateways = [
    "Bitcoin",
    "Ethereum",
    "Usdt",
    "Sol",
    "Bank Transfer",









    //   "Binance",
//   "Coinbase",
//   "Bybit",
//   "Kraken",
//   "OKX",
//   "KuCoin",
//   "Bitstamp",
//   "Gate.io",
//   "Crypto.com",
//   "Bitfinex",
//   "Huobi",
//   "MEXC",
//   "CoinEx",
//   "Paxful",
//   "Trust Wallet",
//   "MetaMask",
//   "Ledger",
//   "Blockchain.com",
//   "Gemini",
//   "Robinhood Crypto",
];

export const transactionAmounts = Array.from({ length: 200 }).map(
  (_, i) => {
    const base = 300 + i * 25;
    const noise = Math.floor(Math.random() * 500);
    const value = base + noise;

    return value;
  }
);